# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ysyx/zzq/cdp_ede_local-Lab08_exp21/mycpu_env/soc_verify/soc_axi/run_vivado/project/Cache/ip/data_bank/data_bank.xci
# IP: The module: 'data_bank' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ysyx/zzq/cdp_ede_local-Lab08_exp21/mycpu_env/soc_verify/soc_axi/run_vivado/project/Cache/ip/data_bank/data_bank_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_bank'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/ysyx/zzq/cdp_ede_local-Lab08_exp21/mycpu_env/soc_verify/soc_axi/run_vivado/project/Cache/ip/data_bank/data_bank.xci
# IP: The module: 'data_bank' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ysyx/zzq/cdp_ede_local-Lab08_exp21/mycpu_env/soc_verify/soc_axi/run_vivado/project/Cache/ip/data_bank/data_bank_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_bank'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
